# fly.toml app configuration file generated for disasterlink-api on 2025-06-01T14:34:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'disasterlink-api'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
